version: '3.8'
services:
  queryservice:
    container_name: query-service
    build: .
    tty: true
    volumes:
      - ./app:/go/src/query
    ports:
      - 8083:8083
    networks:
      - external
networks:
  external:
    name: sampledb_net
    external: true