// バージョン3を利用する

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: proto/category.proto

// パッケージの宣言

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CategtoryService_List_FullMethodName = "/proto.CategtoryService/List"
	CategtoryService_ById_FullMethodName = "/proto.CategtoryService/ById"
)

// CategtoryServiceClient is the client API for CategtoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategtoryServiceClient interface {
	// すべてのカテゴリを取得して返す
	List(ctx context.Context, in *CategoryParam, opts ...grpc.CallOption) (*CategoriesResult, error)
	// 指定されたIDのカテゴリを取得して返す
	ById(ctx context.Context, in *CategoryParam, opts ...grpc.CallOption) (*CategoryResult, error)
}

type categtoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategtoryServiceClient(cc grpc.ClientConnInterface) CategtoryServiceClient {
	return &categtoryServiceClient{cc}
}

func (c *categtoryServiceClient) List(ctx context.Context, in *CategoryParam, opts ...grpc.CallOption) (*CategoriesResult, error) {
	out := new(CategoriesResult)
	err := c.cc.Invoke(ctx, CategtoryService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categtoryServiceClient) ById(ctx context.Context, in *CategoryParam, opts ...grpc.CallOption) (*CategoryResult, error) {
	out := new(CategoryResult)
	err := c.cc.Invoke(ctx, CategtoryService_ById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategtoryServiceServer is the server API for CategtoryService service.
// All implementations must embed UnimplementedCategtoryServiceServer
// for forward compatibility
type CategtoryServiceServer interface {
	// すべてのカテゴリを取得して返す
	List(context.Context, *CategoryParam) (*CategoriesResult, error)
	// 指定されたIDのカテゴリを取得して返す
	ById(context.Context, *CategoryParam) (*CategoryResult, error)
	mustEmbedUnimplementedCategtoryServiceServer()
}

// UnimplementedCategtoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCategtoryServiceServer struct {
}

func (UnimplementedCategtoryServiceServer) List(context.Context, *CategoryParam) (*CategoriesResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCategtoryServiceServer) ById(context.Context, *CategoryParam) (*CategoryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ById not implemented")
}
func (UnimplementedCategtoryServiceServer) mustEmbedUnimplementedCategtoryServiceServer() {}

// UnsafeCategtoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategtoryServiceServer will
// result in compilation errors.
type UnsafeCategtoryServiceServer interface {
	mustEmbedUnimplementedCategtoryServiceServer()
}

func RegisterCategtoryServiceServer(s grpc.ServiceRegistrar, srv CategtoryServiceServer) {
	s.RegisterService(&CategtoryService_ServiceDesc, srv)
}

func _CategtoryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategtoryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategtoryService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategtoryServiceServer).List(ctx, req.(*CategoryParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategtoryService_ById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategtoryServiceServer).ById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategtoryService_ById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategtoryServiceServer).ById(ctx, req.(*CategoryParam))
	}
	return interceptor(ctx, in, info, handler)
}

// CategtoryService_ServiceDesc is the grpc.ServiceDesc for CategtoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategtoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CategtoryService",
	HandlerType: (*CategtoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CategtoryService_List_Handler,
		},
		{
			MethodName: "ById",
			Handler:    _CategtoryService_ById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/category.proto",
}
